apiVersion: batch/v1
kind: Job
metadata:
   name: postupgrade-hook
   annotations:
       "helm.sh/hook": "post-upgrade"
       "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    spec:
      containers:
      - name: health-check-container
        image: maheshkasbe/hook:v2
        command: ["/bin/sh", "-c"]
        args:
        - |
            lua healthcheck.lua rollouts default
      restartPolicy: Never
      serviceAccountName: default